export { default as HomePage} from "./Home.page"
export { default as LoginPage} from "./Login.page"
export { default as RegisterPage} from "./Register.page"
export { default as ContactAppPage} from "./ContactAdd.page"
export { default as ContactPage} from "./Contact.page"